////
Module included in the following assemblies:
-service_mesh/v2x/ossm-security.adoc
////

[id="ossm-vs-istio_{context}"]
= Role Based Access Control (RBAC)

Role-based access control (RBAC) objects determine whether a user or service is allowed to perform a given action within a project. You can define mesh-, namespace-, and workload-wide access control for your workloads in the mesh. 

To configure RBAC, create an `AuthorizationPolicy` resource in the namespace for which you are configuring access. If you are configuring mesh-wide access, use `istio-system`. The namespace must match your `metadata.namespace` field.

For example, with RBAC, you can create policies that:

* Configure intra-project communication.
* Allow or deny full access to all workloads in the default namespace.
* Configure ingress gateway access.
* Require a token for access,

An authorization policy includes a selector, an action, and a list of rules:

* The `selector` field specifies the target of the policy.
* The `action` field specifies whether to allow or deny the request.
* The `rules` specify when to trigger the action.
** The `from` field specifies constraints on the request origin.
** The `to` field specifies constraints on request target and parameters.
** The `when` field specifies additional conditions that to apply the rule.

.Procedure

1. Construct your `AuthorizationPolicy` resource. The following example shows a resource that updates the ingress-policy `AuthorizationPolicy` to deny an IP address from accessing the ingress gateway.
+
[source,yaml]
----
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: DENY
  rules:
  - from:
    - source:
      ipBlocks: ["1.2.3.4"]
----
+
2. Run the following command after you write your resource to create your resource in your namespace. The namespace must match your `metadata.namespace` field.
+
[source,terminal]
----
$ oc create -n istio-system -f <filename> 
----
+
3. Consider the following examples for other common configurations.

== Configure intra-project communication

You can use `AuthorizationPolicy` to configure your control plane to allow or deny the traffic communicating with your mesh or services in your mesh. 

=== Restrict access to services outside a namespace

You can deny requests from any source that is not in the `bookinfo` namespace with the following `AuthorizationPolicy` resource example.

[source,yaml]
----
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: httpbin-deny
 namespace: bookinfo
spec:
 selector:
   matchLabels:
     app: httpbin
     version: v1
 action: DENY
 rules:
 - from:
   - source:
       notNamespaces: ["bookinfo"]
----

=== Creating allow-all and default deny-all authorization policies

The following example shows an allow-all authorization policy that allows full access to all workloads in the `bookinfo` namespace.

[source,yaml]
----
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all
  namespace: bookinfo
spec:
  action: ALLOW
  rules:
  - {}
----

The following example shows a policy that denies any access to all workloads in the `bookinfo` namespace.

[source,yaml]
----
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: bookinfo
spec:
  {}
----

== Allow or deny access to the ingress gateway

You can set an authorization policy to add allow or deny lists based on IP addresses.

[source,yaml]
----
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
  - from:
    - source:
       ipBlocks: ["1.2.3.4", "5.6.7.0/24"]
----

== Set restricted access with JSON Web Token

To configure what can access services in your mesh, you can restrict access with a JSON Web Token (JWT). After authentication, a user or service can access routes, services that are associated with that token. 

1. Create a `RequestAuthentication` resource, which defines the methods are supported by a workload. The following example accepts a JWT issued by `http://localhost:8080/auth/realms/master`.
+
[source,yaml]
----
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-example"
  namespace: bookinfo
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: http://localhost:8080/auth/realms/master
    jwksUri: "http://keycloak.default.svc:8080/auth/realms/master/protocol/openid-connect/certs"
----
+
2. You must pair the `RequestAuthentication` resource with an `AuthorizationPolicy` resource. Create the `AuthorizationPolicy` resource in the same namespace. The following example requires a JWT from `httpbin` workloads.
+
[source,yaml]
----
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "frontend-ingress"
  namespace: bookinfo
spec:
  selector:
    matchLabels:
      app: httpbin
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]
----

